# Generated by Django 5.1 on 2024-09-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('hero', models.CharField(max_length=50)),
                ('heroine', models.CharField(max_length=50)),
            ],
        ),
    ]
