# Generated by Django 5.1 on 2024-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('mail_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'StudentTable',
                'verbose_name_plural': 'StudentTables',
            },
        ),
    ]
